### ISSUE TITLE
Set up PostgreSQL Database with Docker

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Backend#2]
## 📝 Description
Create a Docker-based PostgreSQL database setup with proper configuration files and environment variables for development and production environments.

## 📜 Tasks
1. Create a Docker Compose configuration
2. Set up PostgreSQL environment variables
3. Create initialization scripts
4. Configure database volumes
5. Add health checks
6. Document connection details

### Docker Compose Configuration
Create a docker-compose.yml file in the project root with the following content:

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydatabase}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
### Environment Variables
Create a .env file in the project root:

POSTGRES_DB=mydatabase
POSTGRES_USER=myuser
POSTGRES_PASSWORD=mypassword
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
### Database Initialization Script
Create a directory init-scripts and add 01-init.sql:

-- Create extensions if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create example table
CREATE TABLE IF NOT EXISTS example_table (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add any initial data if needed
INSERT INTO example_table (name) VALUES ('Example Record');
## Connection Details
- Host: localhost (or postgres if connecting from another container)
- Port: 5432
- Database: mydatabase
- Username: myuser
- Password: mypassword

## Usage Instructions
1. Make sure Docker and Docker Compose are installed
2. Clone the repository
3. Copy the .env.example to .env and adjust values if needed
4. Run:
   
bash
   docker-compose up -d
   
5. Verify the container is running:
   
bash
   docker-compose ps
   
## 📋 Additional Notes
- Data is persisted in a named volume postgres_data
- Database initialization scripts in init-scripts run automatically on first startup
- Health checks ensure the database is ready before accepting connections
- The database is accessible on port 5432

We will be very happy to see your applications, good luck! 🌾

**Comment by gregemax** [comment]
May I pick this up?
Hi, I’m Emmanuel Greg, a backend developer with experience in Docker, PostgreSQL, and backend system configuration. I’d like to work on setting up the PostgreSQL database with Docker for this project.

Docker Compose: Configure the docker-compose.yml for PostgreSQL setup with proper environment variables.
Environment Variables: Set up .env for development and production environments.
Initialization Scripts: Create initialization scripts for database setup and data insertion.
Health Checks: Add health checks to ensure database readiness.
Documentation: Document the connection details and usage instructions.

I’ve reviewed the Contributor’s Guide and am excited to contribute. May I pick this up?

**Comment by mimisavage** [comment]
Can I tackle this one?

**Comment by derianrddev** [comment]
**Hello Revolutionary Farmers team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I am very excited about the opportunity to contribute to your project based on [ecosystem] during the **Only Dust 11 Hackathon** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js), PostgreSQL.
- **Web3:** Cairo.

I am committed to actively collaborating, delivering quality code, and maintaining good communication with the team.

Here are my profiles for more details:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in building scalable backend and database solutions for Web3 and software development. I’ve contributed to several projects, where I ensured efficient database integration and containerized setups, making me confident in handling this task.

To tackle this issue:

I’ll create a Docker Compose configuration with PostgreSQL, using environment variables for development and production flexibility.
Add initialization scripts to set up tables and extensions (e.g., UUID generation).
Configure volumes for persistent data storage and health checks to validate database readiness.
Document connection details for developers, ensuring smooth onboarding.
ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Michaelkingsdev** [comment]
Would love to tackle this!

**Comment by Supa-mega** [comment]
please ,Can I tackle this one ?

**Comment by suhas-sensei** [comment]
Could I grab this task? "I'll set up a Docker-based PostgreSQL configuration with proper environment handling and initialization scripts. Having experience with Docker and PostgreSQL deployments in previous odhack, I'll ensure secure configuration with health checks and volume persistence.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by Ugo-X** [comment]
hello Project Maintainer, please I would like to be assigned to this issue

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


The implementation involves creating a docker-compose.yml file to configure the PostgreSQL service, including environment variables for the database name, user, password, and data storage volume. Additionally, initialization scripts are placed in the init-scripts folder to create necessary database extensions and sample data on the first run. Health checks are incorporated to ensure the database is ready before accepting connections, and a .env file is provided to manage environment variables. After setting up Docker Compose, use the commands docker-compose up -d to run the service and docker-compose ps to verify that the container is running correctly. Data persistence is managed through a named volume (postgres_data), and the database is accessible on port 5432, with connection details clearly documented for easy integration.

**Comment by DuendexCR** [comment]
Can I take this issue?

**Comment by tosinmoses384** [comment]
Can I handle this task?

**Comment by salazarsebas** [comment]
Done!
