### ISSUE TITLE
Set up NestJS Backend Structure with PostgreSQL Integration

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Backend#3]
## Description
Create the initial backend structure using NestJS framework, implementing a modular architecture with proper database integration using the previously configured PostgreSQL Docker setup.

### Project Setup
```
# Initial setup commands
nest new farmers-marketplace-api
cd farmers-marketplace-api
npm install @nestjs/typeorm typeorm pg
npm install @nestjs/config
npm install class-validator class-transformer
npm install bcrypt @types/bcrypt
npm install @nestjs/jwt @nestjs/passport passport passport-jwt
```

### Project Structure
src/
├── config/
│   ├── database.config.ts
│   ├── jwt.config.ts
│   └── swagger.config.ts
├── common/
│   ├── decorators/
│   ├── filters/
│   ├── guards/
│   ├── interceptors/
│   └── pipes/
├── modules/
│   ├── auth/
│   ├── users/
│   ├── products/
│   ├── farmers/
│   ├── orders/
│   └── categories/
├── shared/
│   ├── interfaces/
│   ├── dto/
│   └── entities/
├── app.module.ts
└── main.ts

### Database Configuration
Create config/database.config.ts:
```
import { registerAs } from '@nestjs/config';

export default registerAs('database', () => ({
  type: 'postgres',
  host: process.env.POSTGRES_HOST || 'localhost',
  port: parseInt(process.env.POSTGRES_PORT, 10) || 5432,
  username: process.env.POSTGRES_USER || 'myuser',
  password: process.env.POSTGRES_PASSWORD || 'mypassword',
  database: process.env.POSTGRES_DB || 'mydatabase',
  entities: ['dist/**/*.entity{.ts,.js}'],
  synchronize: process.env.NODE_ENV !== 'production',
  logging: process.env.NODE_ENV !== 'production',
}));
```
#### App Module
```
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import databaseConfig from './config/database.config';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      load: [databaseConfig],
    }),
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        ...configService.get('database'),
      }),
    }),
    // Feature modules will be imported here
  ],
})
export class AppModule {}
```
#### Base Entity
```
import { 
  PrimaryGeneratedColumn, 
  CreateDateColumn, 
  UpdateDateColumn 
} from 'typeorm';

export abstract class BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
```

### Example Feature Module (Products)
```
// modules/products/entities/product.entity.ts
import { Entity, Column, ManyToOne } from 'typeorm';
import { BaseEntity } from '@shared/entities/base.entity';

@Entity('products')
export class Product extends BaseEntity {
  @Column()
  name: string;

  @Column('text')
  description: string;

  @Column('decimal', { precision: 10, scale: 2 })
  price: number;

  @Column()
  unit: string;

  @Column('json', { nullable: true })
  images: string[];

  @Column()
  stockQuantity: number;

  @Column({ type: 'timestamp' })
  harvestDate: Date;
}
```
### Environment Setup
Create .env file:
```
# Server
PORT=3000
NODE_ENV=development

# Database
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=myuser
POSTGRES_PASSWORD=mypassword
POSTGRES_DB=mydatabase

# JWT
JWT_SECRET=your-secret-key
JWT_EXPIRATION=1d
```
### Docker Integration
Update docker-compose.yml to include the NestJS application:
```yaml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmers_marketplace_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:

**Comment by gregemax** [comment]
Is it okay if I take this?
 a backend developer with 3 years of experience in NestJS, PostgreSQL, and scalable API design. I’d like to take on this task to set up the project’s backend structure.
I’ve reviewed the Contributor’s Guide and am ready to contribute. May I pick this up?
you can check my github proof

**Comment by derianrddev** [comment]
**Hello Revolutionary Farmers team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I am very excited about the opportunity to contribute to your project based on [ecosystem] during the **Only Dust 11 Hackathon** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js), PostgreSQL.
- **Web3:** Cairo.

I am committed to actively collaborating, delivering quality code, and maintaining good communication with the team.

Here are my profiles for more details:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
To tackle this issue:

Set up a NestJS project with TypeORM and environment-based configurations for PostgreSQL.
Implement a modular structure, including shared BaseEntity and feature modules like Products, Users, and Orders.
Configure a .env file for environment-specific settings and Docker Compose for containerized deployment.
Add initialization scripts and health checks for PostgreSQL integration.
ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Michaelkingsdev** [comment]
I'd like to take this issue.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.
